#!/usr/bin/env python3
"""Personal decisions digest — what is waiting on THIS person, from their vault.

Prints a short plain-text digest to stdout for `hermes cron --no-agent`
delivery. **Empty stdout = silent**, which is the whole point: a nudge that
reports "nothing waiting" every morning teaches its reader to filter the
channel, and then the message that mattered gets filtered too. Silence is
mechanical here, not a instruction an LLM has to remember to obey.

Non-zero exit on hard failures so cron alerts instead of failing quietly. A
missing Shares.md is NOT a failure — it is the ordinary state of a person with
nothing pending, and must stay silent.

Reads only the compiled vault. No master access, no network, no writes.
"""
from __future__ import annotations

import os
import re
import sys
from datetime import date

VAULT = os.environ.get("BRAIN_VAULT") or "/vault"
PERSON = os.environ.get("BRAIN_PERSON") or ""
# Own proposals are not action for the reader — mention one only once it has
# been sitting long enough that silence has become the anomaly.
STALE_AFTER_DAYS = int(os.environ.get("BRAIN_STALE_DAYS") or "5")

# Section headings generated by brain (promotions.py / shares.py). Two of these
# are things waiting on the reader; the third is their own proposals waiting on
# someone else.
DECIDE_PROMOTIONS = "## Promotions awaiting your decision"
DECIDE_SHARES = "## Awaiting your decision"
OWN_PENDING = "## Awaiting approval"


def _person_id() -> str:
    if PERSON:
        return PERSON
    people = os.path.join(VAULT, "People")
    try:
        entries = [d for d in os.listdir(people)
                   if os.path.isdir(os.path.join(people, d))]
    except OSError:
        return ""
    # A compiled slice contains exactly one person's own space.
    return entries[0] if len(entries) == 1 else ""


def _sections(text: str) -> dict[str, list[str]]:
    """Split on `## ` headings, keeping each heading's body lines."""
    out: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines():
        if line.startswith("## "):
            current = line.strip()
            out[current] = []
        elif current is not None:
            out[current].append(line)
    return out


def _bullets(lines: list[str]) -> list[str]:
    return [ln.strip()[2:].strip() for ln in lines if ln.strip().startswith("- ")]


def _items(body: list[str]) -> list[str]:
    """Promotion entries are `### ` headings; share entries are `- ` bullets."""
    heads = [ln.strip().lstrip("#").strip()
             for ln in body if ln.strip().startswith("### ")]
    return heads or _bullets(body)


_DATE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")


def _age_days(line: str, today: date) -> int | None:
    found = _DATE.findall(line)
    if not found:
        return None
    try:
        return (today - date.fromisoformat(found[-1])).days
    except ValueError:
        return None


def main() -> int:
    pid = _person_id()
    if not pid:
        # Can't identify whose vault this is. Not actionable, and guessing
        # would be worse than saying nothing.
        return 0
    path = os.path.join(VAULT, "People", pid, "Shares.md")
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    except FileNotFoundError:
        return 0  # nothing has ever been pending — the quiet, normal case
    except OSError as e:
        print(f"cannot read {path}: {e}", file=sys.stderr)
        return 1

    sections = _sections(text)
    today = date.today()
    out: list[str] = []

    promos = _items(sections.get(DECIDE_PROMOTIONS, []))
    if promos:
        out.append(f"{len(promos)} promotion(s) awaiting your decision:")
        out += [f"  • {p}" for p in promos]

    shares = _items(sections.get(DECIDE_SHARES, []))
    if shares:
        out.append(f"{len(shares)} share request(s) awaiting your decision:")
        out += [f"  • {s}" for s in shares]

    stale = [(b, d) for b in _bullets(sections.get(OWN_PENDING, []))
             if (d := _age_days(b, today)) is not None and d >= STALE_AFTER_DAYS]
    if stale:
        out.append(f"Your own proposal(s) still pending after "
                   f"{STALE_AFTER_DAYS}+ days:")
        out += [f"  • {b}  ({d} days)" for b, d in stale]

    if not out:
        return 0  # THE point of this script

    print(f"Waiting on you in the brain ({pid}):")
    print()
    print("\n".join(out))
    print()
    print("Decide by telling me plainly to approve or reject one — I record "
          "only a decision you have explicitly made. Full detail, including "
          f"what would be published, is in People/{pid}/Shares.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
